# SPDX-FileCopyrightText: © 2026 Team CharLS
# SPDX-License-Identifier: BSD-3-Clause

# This is a configuration file for the reuse lint tool. It allows specifying license info
# for files that cannot be extended with such info.

version = 1

[[annotations]]
path = [
    "**.jls",
    "**.raw",
    "**.json",
    "**.json.in",
    "**.png",
    "**.ico",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "© 2026 Team CharLS"
SPDX-License-Identifier = "BSD-3-Clause"
